### ISSUE TITLE
Problème dans les déclenchement d événements

### ISSUE THREAD

**Issue by C3DR1K** [GladysProject/Gladys-Android#2]
**describe the bug**
Problème sur les trois derniers événements :
La fonction "utilisateur doit se réveiller " devient "utilisateur vu à la maison" dans la time Line" ;
La fonction "utilisateur vu a la maison" devient "va se coucher" dans la TimeLine ;
Et la fonction "va se coucher" fait fermer l application...

**Platform Details (please complete the following information):**
 - Device: Wiko Rainbow Lite 4g
 - OS: android 5.1.1

**Comment by MathieuAndrade** [comment]
Merci pour le retour ! 
C'est corrigé 1d211e4ddea5b92637e3d719fd619c1d8f688f01 😁
